version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=park
      - MYSQL_PASSWORD=123
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

  app:
    depends_on:
      - mysql
    container_name: app
    build: .
    ports:
      - '8080:8080'
    environment:
      HOST: mysql
      PORT: 3306
    restart: on-failure

volumes:
  db_data:
